# Gabriel Soares Baptista
# Humberto Giuri Calente
# João Lucas Luz Lima
TARGET = pipes
CXX = gcc
OBJS = pipes.c

pipes:$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS)

clean:
	rm -rf *.o

run:$(TARGET)
	./$(TARGET)
